/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaiDesktopView.java
 *
 * Created on Jun 27, 2011, 10:14:41 AM
 */
package paidesktop;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author banyaai
 */
public class PaiDesktopView extends javax.swing.JFrame {

    ArrayList<Candidate> candidatesList = new ArrayList<Candidate>();

    /** Creates new form PaiDesktopView */
    public PaiDesktopView() {
        GetParameters getParameters = new GetParameters();
        candidatesList = getParameters.getCandidatesList();
        jRadioButton1 = new JRadioButton[candidatesList.size()];
        for (int i = 0; i < candidatesList.size(); i++) {
            jRadioButton1[i] = new JRadioButton(candidatesList.get(i).getName());
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthorizationPanel = new javax.swing.JPanel();
        AnonymousInfoPanel = new javax.swing.JPanel();
        AnonymousInfoLabel = new javax.swing.JLabel();
        AuthorizationCheckPanel = new javax.swing.JPanel();
        PersonIDLabel = new javax.swing.JLabel();
        DocumentIDLabel = new javax.swing.JLabel();
        PersonIDText = new javax.swing.JTextField();
        DocumentIDText = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        VotePanel = new javax.swing.JPanel();
        VoteButtonCheckPanel = new javax.swing.JPanel();
        CandidatesLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OKButton2 = new javax.swing.JButton();
        CacnelButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("paidesktop/properties/PaiDesktopView"); // NOI18N
        AnonymousInfoLabel.setText(bundle.getString("AnonymousInfoLabel.Text")); // NOI18N

        javax.swing.GroupLayout AnonymousInfoPanelLayout = new javax.swing.GroupLayout(AnonymousInfoPanel);
        AnonymousInfoPanel.setLayout(AnonymousInfoPanelLayout);
        AnonymousInfoPanelLayout.setHorizontalGroup(
            AnonymousInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnonymousInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnonymousInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
                .addContainerGap())
        );
        AnonymousInfoPanelLayout.setVerticalGroup(
            AnonymousInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnonymousInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnonymousInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );

        PersonIDLabel.setText(bundle.getString("PersonIDLabel.Text")); // NOI18N

        DocumentIDLabel.setText(bundle.getString("DocumentIDLabel.Text")); // NOI18N

        OKButton.setText(bundle.getString("OKButton.Text")); // NOI18N
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText(bundle.getString("CancelButton.Text")); // NOI18N
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AuthorizationCheckPanelLayout = new javax.swing.GroupLayout(AuthorizationCheckPanel);
        AuthorizationCheckPanel.setLayout(AuthorizationCheckPanelLayout);
        AuthorizationCheckPanelLayout.setHorizontalGroup(
            AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorizationCheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AuthorizationCheckPanelLayout.createSequentialGroup()
                        .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DocumentIDLabel)
                            .addComponent(PersonIDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PersonIDText)
                            .addComponent(DocumentIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGap(120, 120, 120))
                    .addComponent(OKButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        AuthorizationCheckPanelLayout.setVerticalGroup(
            AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorizationCheckPanelLayout.createSequentialGroup()
                .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AuthorizationCheckPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PersonIDLabel)
                            .addComponent(PersonIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DocumentIDLabel)
                            .addComponent(DocumentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AuthorizationCheckPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(AuthorizationCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OKButton)
                            .addComponent(CancelButton))))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AuthorizationPanelLayout = new javax.swing.GroupLayout(AuthorizationPanel);
        AuthorizationPanel.setLayout(AuthorizationPanelLayout);
        AuthorizationPanelLayout.setHorizontalGroup(
            AuthorizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthorizationPanelLayout.createSequentialGroup()
                .addComponent(AuthorizationCheckPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthorizationPanelLayout.createSequentialGroup()
                .addComponent(AnonymousInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        AuthorizationPanelLayout.setVerticalGroup(
            AuthorizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorizationPanelLayout.createSequentialGroup()
                .addComponent(AnonymousInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AuthorizationCheckPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CandidatesLabel.setText(bundle.getString("CandidatesLabel.Text")); // NOI18N

        javax.swing.GroupLayout VoteButtonCheckPanelLayout = new javax.swing.GroupLayout(VoteButtonCheckPanel);
        VoteButtonCheckPanel.setLayout(VoteButtonCheckPanelLayout);
        VoteButtonCheckPanelLayout.setHorizontalGroup(
            VoteButtonCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteButtonCheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidatesLabel)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        VoteButtonCheckPanelLayout.setVerticalGroup(
            VoteButtonCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoteButtonCheckPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidatesLabel)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        OKButton2.setText("OKButton");
        OKButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButton2ActionPerformed(evt);
            }
        });

        CacnelButton2.setText("CancelButton");
        CacnelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CacnelButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(OKButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CacnelButton2)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton2)
                    .addComponent(CacnelButton2))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout VotePanelLayout = new javax.swing.GroupLayout(VotePanel);
        VotePanel.setLayout(VotePanelLayout);
        VotePanelLayout.setHorizontalGroup(
            VotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VotePanelLayout.createSequentialGroup()
                .addComponent(VoteButtonCheckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );
        VotePanelLayout.setVerticalGroup(
            VotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VoteButtonCheckPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VotePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AuthorizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(VotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AuthorizationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(VotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("paidesktop.properties/PaiDesktopView");

        if (!checkText(PersonIDText.getText())) {
            JOptionPane.showMessageDialog(null, bundle.getString("PersonID.WrongString"));
        } else if (!checkText(DocumentIDText.getText())) {
            JOptionPane.showMessageDialog(null, bundle.getString("DocumentID.WrongString"));
        } else {

            int choice = JOptionPane.showConfirmDialog(null, bundle.getString("CheckAuthenticationData.Text") + "\n\n" + bundle.getString("PersonIDLabel.Text")
                    + PersonIDText.getText() + "\n" + bundle.getString("DocumentIDLabel.Text") + DocumentIDText.getText());
//      if("Yes") then buduj panel glosowania
            if (choice == 0) {
                AuthorizationPanel.setVisible(false);
                VotePanel.setVisible(true);


                javax.swing.GroupLayout VoteButtonCheckPanelLayout = new javax.swing.GroupLayout(VoteButtonCheckPanel);
                ParallelGroup parallelGroup1 = VoteButtonCheckPanelLayout.createParallelGroup();
                SequentialGroup sequentialGroup = VoteButtonCheckPanelLayout.createSequentialGroup();
                sequentialGroup.addGap(32, 32, 32);
                for (int i = 0; i < candidatesList.size(); i++) {
                    jRadioButton1[i] = new JRadioButton(candidatesList.get(i).getName()); // wywalic
                    System.out.println(jRadioButton1[i].getText());
                    parallelGroup1.addComponent(jRadioButton1[i]);
                    sequentialGroup.addComponent(jRadioButton1[i]);
                    sequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED);
                    candidatesButtonGroup.add(jRadioButton1[i]);
                }

                sequentialGroup.addContainerGap(/*przesuwanie w zaleznosci od ilosci kandydatow*/445 - 26 * candidatesList.size(), Short.MAX_VALUE);

                VoteButtonCheckPanel.setLayout(VoteButtonCheckPanelLayout);
                VoteButtonCheckPanelLayout.setHorizontalGroup(
                        VoteButtonCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).
                        addGroup(VoteButtonCheckPanelLayout.createSequentialGroup().addContainerGap().addGroup(parallelGroup1).addContainerGap(175, Short.MAX_VALUE)));

                VoteButtonCheckPanelLayout.setVerticalGroup(
                        VoteButtonCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(sequentialGroup));

                javax.swing.GroupLayout VotePanelLayout = new javax.swing.GroupLayout(VotePanel);
                VotePanel.setLayout(VotePanelLayout);
                VotePanelLayout.setHorizontalGroup(
                        VotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(VotePanelLayout.createSequentialGroup().addComponent(VoteButtonCheckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(1025, Short.MAX_VALUE)));
                VotePanelLayout.setVerticalGroup(
                        VotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(VoteButtonCheckPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

            } //      if("No") then nie rob nic
            else if (choice == -1) {
            } //      if("Cancel") then przerwij glosowanie
            else {
                PersonIDText.setText("");
                DocumentIDText.setText("");
            }
        }
    }//GEN-LAST:event_OKButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        PersonIDText.setText("");
        DocumentIDText.setText("");
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButton2ActionPerformed
        // TODO add your handling code here:
        endVote(true);
    }//GEN-LAST:event_OKButton2ActionPerformed

    private void CacnelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CacnelButton2ActionPerformed
        // TODO add your handling code here:
        endVote(false);
    }//GEN-LAST:event_CacnelButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PaiDesktopView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnonymousInfoLabel;
    private javax.swing.JPanel AnonymousInfoPanel;
    private javax.swing.JPanel AuthorizationCheckPanel;
    private javax.swing.JPanel AuthorizationPanel;
    private javax.swing.JButton CacnelButton2;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CandidatesLabel;
    private javax.swing.JLabel DocumentIDLabel;
    private javax.swing.JTextField DocumentIDText;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton OKButton2;
    private javax.swing.JLabel PersonIDLabel;
    private javax.swing.JTextField PersonIDText;
    private javax.swing.JPanel VoteButtonCheckPanel;
    private javax.swing.JPanel VotePanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JRadioButton jRadioButton1[];
    ButtonGroup candidatesButtonGroup = new ButtonGroup();

    void endVote(boolean sendVote) {
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("paidesktop.properties/PaiDesktopView");

        if (candidatesButtonGroup.getSelection() != null) {
            JOptionPane.showMessageDialog(null, bundle.getString("ThankYou.Text"));
            AuthorizationPanel.setVisible(true);
            VotePanel.setVisible(false);
        } else {

            int choice = JOptionPane.showConfirmDialog(null, bundle.getString("AreYouSure.Text"));
            if (choice == 0) {
                JOptionPane.showMessageDialog(null, bundle.getString("ThankYou.Text"));
                AuthorizationPanel.setVisible(true);
                VotePanel.setVisible(false);
                if (candidatesButtonGroup.getSelection() != null) {
                    //send vote
                }
            }
        }
        if (candidatesButtonGroup.getSelection() != null) {
            candidatesButtonGroup.clearSelection();
        }

    }

    boolean checkText(String text) {

        //It can't contain only numbers if it's null or empty...
        if (text == null || text.length() == 0) {
            return false;
        }

        for (int i = 0; i < text.length(); i++) {

            //If we find a non-digit character we return false.

            if (!Character.isLetterOrDigit(text.charAt(i))) {
                return false;
            }

        }

        return true;
    }
}
